.TH CSV\-TO\-XLSX 1 "November 7, 2013" 
.SH NAME
.PP
csv\-to\-xlsx \- convert CSV files to XLSX worksheets
.SH SYNOPSIS
.PP
csv\-to\-xlsx \-o|\-\-output\-file XLSX_PATH CSV_PATH ...
.SH DESCRIPTION
.PP
Create an XLSX workbook from the CSV files specified on the command
line.
.PP
Each CSV file becomes a worksheet in the workbook.
.PP
The names of the worksheets are derived from CSV file names.
Excel worksheet names are limited to 31 characters and these characters
are forbidden:
.IP
.nf
\f[C]
[\ ]\ *\ ?\ /\ \\\ .
\f[]
.fi
.PP
\f[C]csv\-to\-xlsx\f[] replaces forbidden characters with spaces,
squeezes multiple adjacents spaces to a single space, truncates to 31
characters, and trims marginal space.
If this results in multiple sheets with the same name an error is
generated.
.PP
XLSX is the default format used by Excel 2007 and later.
.SH OPTIONS
.PP
\-o DELIMITER, \-\-output\-file PATH : the PATH of the XLSX file to
create.
It must have an .xlsx suffix.
.SH SEE ALSO
.PP
\f[C]xlsx\-to\-csv\f[] (1)
.PP
http://www.ietf.org/rfc/rfc4180.txt
.PP
http://www.ecma\-international.org/publications/standards/Ecma\-376.htm
.SH AUTHORS
Clark Grubb.
