.TH HEADER\-SORT 1 "June 4, 2013" 
.SH NAME
.PP
header\-sort \- sort file with header
.SH SYNOPSIS
.PP
header\-sort [OPTIONS] FILE
.SH DESCRIPTION
.PP
Like \f[C]sort\f[], but the position of the first line is preserved.
.SH OPTIONS
.PP
See \f[C]sort\f[] for available options.
.SH SEE ALSO
.PP
\f[C]sort\f[] (1)
.SH AUTHORS
Clark Grubb.
