.TH JSON\-DIFF 1 "July 29, 2014" 
.SH NAME
.PP
json\-diff \- run diff on two JSON documents
.SH SYNOPSIS
.PP
json\-diff PATH1 PATH2
.SH DESCRIPTION
.PP
Run \f[C]diff\f[] on two JSON documents.
Each document is normalized using \f[C]python\ \-mjson.tool\f[].
.SH OPTIONS
.PP
none
.SH SEE ALSO
.PP
\f[C]diff\f[] (1)
.SH AUTHORS
Clark Grubb.
