.TH SET\-DIFF 1 "May 6, 2013" 
.SH NAME
.PP
set\-diff \- find lines in first file which are not in the second
.SH SYNOPSIS
.PP
set\-diff FILE1 FILE2
.SH DESCRIPTION
.PP
List the lines which are in the first file and not in the second.
.PP
The lines are output in a sorted order and not necessarily the order of
the first file.
.SH OPTIONS
.PP
None
.SH SEE ALSO
.PP
\f[C]set\-intersect\f[] (1)
.SH AUTHORS
Clark Grubb.
