.TH SET\-INTERSECT 1 "May 6, 2013" 
.SH NAME
.PP
set\-intersect \- find lines common to two files
.SH SYNOPSIS
.PP
set\-intersect FILE1 FILE2
.SH DESCRIPTION
.PP
List the lines which are in both the first file and the second file.
.SH OPTIONS
.PP
None
.SH SEE ALSO
.PP
\f[C]set\-diff\f[] (1)
.SH AUTHORS
Clark Grubb.
