.TH TAWK 1 "August 16, 2013" 
.SH NAME
.PP
tawk \- version of awk which uses tab character for FS and OFS by
default
.SH SYNOPSIS
.PP
See the awk man page.
.SH DESCRIPTION
.PP
A modified version of awk in which FS and OFS default to the tab
character (ASCII 9).
.PP
The version of awk which was modified is mawk.
.SH OPTIONS
.PP
See the awk or mawk man page.
.SH SEE ALSO
.PP
\f[C]awk\f[] (1), \f[C]mawk\f[] (1)
.SH AUTHORS
Clark Grubb.
