.TH TRIM\-TSV 1 "September 25, 2013" 
.SH NAME
.PP
trim\-tsv \- trim whitespace from fields in a tab delimited file
.SH SYNOPSIS
.PP
trim\-tsv [TSV_FILE]
.SH DESCRIPTION
.PP
Trim whitespace from fields in a tab delimited file.
If no path is specified on the command line, the tool reads from
standard input.
.SH OPTIONS
.PP
none
.SH SEE ALSO
.PP
\f[C]tawk\f[] (1)
.SH AUTHORS
Clark Grubb.
