.TH TSV\-HEADER 1 "March 6, 2015" 
.SH NAME
.PP
tsv\-header \- number the columns in a TSV header
.SH SYNOPSIS
.PP
tsv\-header [TSV_FILE]
.SH DESCRIPTION
.PP
Display the columns of a TSV file header, one per line, with their
ordinal positions.
.PP
The is useful for mapping \f[C]awk\f[] script variables, e.g.
\f[C]$1\f[], \f[C]$2\f[], ..., to column names.
.SH OPTIONS
.PP
none
.SH SEE ALSO
.PP
\f[C]awk\f[] (1), \f[C]tawk\f[] (1), \f[C]check\-tsv\f[] (1)
.SH AUTHORS
Clark Grubb.
