.TH TSV\-TO\-CSV 1 "February 16, 2013" 
.SH NAME
.PP
tsv\-to\-csv \- convert TSV to CSV
.SH SYNOPSIS
.PP
tsv\-to\-csv OPTIONS [TSV_FILE]
.SH DESCRIPTION
.PP
Read a TSV file from file specified on the command line or standard
input and write the corresponding CSV file to standard output.
.PP
In the TSV format fields are delimited by tabs and records are
terminated by an end\-of\-line marker.
.PP
There is no mechanism for quoting tabs or newlines, and by default
\f[C]csv\-to\-tsv\f[] will fail if they occur in the fields of the CSV
file.
.SH OPTIONS
.PP
\-d DELIMITER, \-\-delimiter=DELIMITER : Used to read CSV files which
use DELIMITER to separate fields instead of a comma.
.PP
\-q QUOTECHAR, \-\-quotechar=QUOTECHAR : Used to read CSV files which
use QUOTECHAR to quote fields instead of double quotes.
.PP
\-u, \-\-unescape : Interpret the following backslash sequences when
encountered in the data: , , , \\.
.SH SEE ALSO
.PP
\f[C]csv\-to\-tsv\f[] (1)
.PP
http://www.ietf.org/rfc/rfc4180.txt
.PP
http://www.iana.org/assignments/media\-types/text/tab\-separated\-values
.SH AUTHORS
Clark Grubb.
