.TH UNDERMONGO 1 "May 5, 2014" 
.SH NAME
.PP
undermongo - a mongo shell wrapper which loads underscore.js
.SH SYNOPSIS
.PP
Same as for \f[C]mongo\f[].
.SH DESCRIPTION
.PP
\f[C]underscore.js\f[] will be downloaded.
\f[C]mongo\f[] must already be installed.
.PP
Loading \f[C]underscore.js\f[] makes additional functions available as
attributess of the underscore variable; e.g.
\f[C]_.keys()\f[], \f[C]_.map()\f[].
See the \f[C]underscore.js\f[] docs for a complete list.
.SH OPTIONS
.PP
Same as for \f[C]mongo\f[].
.SH SEE ALSO
.PP
http://docs.mongodb.org/manual/
.PP
http://underscorejs.org/
.SH AUTHORS
Clark Grubb.
