.TH UTF8-SCRIPT 1 "February 14, 2015" 
.SH NAME
.PP
utf8-script - tally characters by UTF-8 script
.SH SYNOPSIS
.PP
utf8-script [-c|--count-ascii|-s|--skip-ascii]
.SH DESCRIPTION
.PP
Tally the characters in the standard input stream by UTF-8 script.
.SH OPTIONS
.PP
-c, --count-ascii : treat ASCII characters as a separate script called
"ASCII".
.PP
-s, --skip-ascii : skip ASCII characters.
Only characters with Unicode point U+0080 and higher are counted.
.SH SEE ALSO
.PP
http://unicode.org/Public/UNIDATA/Scripts.txt
.SH AUTHORS
Clark Grubb.
